# -*- coding: utf-8 -*-
"""Taller_Guiado_Listas_y_Conjuntos_Jose_Gutierrez_1001087923.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gaqc6wxWGKFKAQvE9Fu9USoxRf6MtWdX

Ejercicio 1: Clientes Duplicados y Segmentación

Contexto:

Tienes una lista de clientes con datos repetidos. Además, cuentas con dos listas: clientes activos e inactivos.

Objetivos:

Eliminar duplicados de la lista original.
Identificar clientes en ambos estados.
Encontrar clientes solo activos.
Recorrer los clientes y clasificarlos.
Pistas:

Usa set() para eliminar duplicados.
Usa intersection() para encontrar coincidencias.
Usa difference() para encontrar diferencias.
Usa un for con if para clasificar.
"""

#Jose Luis Gutierrez Jimenez

# Lista original con clientes duplicados
clientes = ["Ana", "Juan", "Pedro", "Ana", "Luis", "Pedro", "Maria"]

# Listas de clientes activos e inactivos
clientes_activos = ["Ana", "Pedro", "Carlos", "Luis"]
clientes_inactivos = ["Juan", "Pedro", "Andres"]

# 1. Eliminar duplicados
clientes_unicos = list(set(clientes))
print("Clientes sin duplicados:", clientes_unicos)


# 2. Clientes en ambos estados
en_ambos = set(clientes_activos).intersection(clientes_inactivos)
print("Clientes en ambos estados:", en_ambos)


# 3. Clientes solo activos
solo_activos = set(clientes_activos).difference(clientes_inactivos)
print("Clientes solo activos:", solo_activos)


# 4. Clasificación con for
print("\nClasificación de clientes:")

for cliente in clientes_unicos:
    if cliente in clientes_activos and cliente in clientes_inactivos:
        print(cliente, "-> Activo e Inactivo")
    elif cliente in clientes_activos:
        print(cliente, "-> Activo")
    elif cliente in clientes_inactivos:
        print(cliente, "-> Inactivo")
    else:
        print(cliente, "-> No clasificado")

"""# Ejercicio 2: Productos y Análisis de Inventario

Ejercicio 2: Productos y Análisis de Inventario

Contexto: Tienes una lista de productos vendidos y otra de inventario disponible.

Objetivos:

Identificar todos los productos.
Encontrar productos vendidos que están en inventario.
Detectar productos que no se han vendido.
Evaluar productos con una condición usando while.
Pistas:

Usa union() para combinar conjuntos.
Usa & para intersección.
Usa - para diferencia.
Convierte el set a lista para usar while.
"""

# Listas de productos
inventario = {"Laptop", "Mouse", "Teclado", "Monitor"}
vendidos = {"Mouse", "Monitor", "Impresora"}


# 1. Todos los productos (unión)
todos_productos = inventario.union(vendidos)
print("Todos los productos:", todos_productos)


# 2. Productos vendidos que están en inventario
vendidos_en_inventario = inventario & vendidos
print("Vendidos que están en inventario:", vendidos_en_inventario)

# 3. Productos que no se han vendido (solo inventario)
no_vendidos = inventario - vendidos
print("Productos no vendidos:", no_vendidos)


# 4. Evaluar con while
print("\nClasificación de productos:")
lista_productos = list(todos_productos)

i = 0
while i < len(lista_productos):
    producto = lista_productos[i]

    if producto in vendidos_en_inventario:
        print(producto, "-> Vendido (estaba en inventario)")
    elif producto in no_vendidos:
        print(producto, "-> Disponible (no vendido)")
    else:
        print(producto, "-> Vendido pero no estaba en inventario")

    i += 1

"""Ejercicio 3: Estudiantes y Cursos

Ejercicio 3: Estudiantes y Cursos.

Contexto:

Tienes estudiantes inscritos en dos cursos distintos.

Objetivos:

Encontrar estudiantes en ambos cursos.
Identificar estudiantes exclusivos por curso.
Unir todos los estudiantes.
Clasificar estudiantes según su participación.
Pistas:

Usa & para intersección.
Usa difference() para exclusivos.
Usa union() para todos.
Usa for + if para clasificar.
"""

# Curso 1
curso_python = {"Ana", "Juan", "Pedro", "Maria"}

# Curso 2
curso_datos = {"Pedro", "Maria", "Luis", "Carlos"}

# 1. Estudiantes que estan en ambos cursos
ambos_cursos = curso_python & curso_datos
print("Estudiantes que estan en dos cursos:", ambos_cursos)

# 2. Estudiantes que solo estan en un solo curso
solo_curso_python = curso_python - curso_datos
solo_curso_datos = curso_datos - curso_python
print("Estudiantes que solo estan en el curso de python:", solo_curso_python)
print("Estudiantes que solo estan en el curso de datos:", solo_curso_datos)

# 3. Todos los estudiantes
todos_estudiantes = curso_python.union(curso_datos)
print("Todos los estudiantes de los dos cursos:", todos_estudiantes)

# 4. Clasificación con for
print("\nClasificación de estudiantes:")

for estudiante in todos_estudiantes:
    if estudiante in ambos_cursos:
        print(estudiante, "-> El estudiante se encuentra en el curso de python y datos")
    elif estudiante in solo_curso_python:
        print(estudiante, "-> El estudiante se encuentra en el curso de python")
    elif estudiante in solo_curso_datos:
        print(estudiante, "-> El estudiante se encuentra en el curso de datos")
    else:
        print(estudiante, "-> No se encuentra en ningun curso")